#!/data/data/com.termux/files/usr/bin/bash
HOST="https://joshuado.es/winehangover"
INST="$TMPDIR"
SCRIPT="hangover-installer"

pkg install -y wget
mkdir -p "$INST"
wget -O "$INST/$SCRIPT" "$HOST/$SCRIPT"
chmod +x "$INST/$SCRIPT"
bash "$INST/$SCRIPT"
rm "$INST/$SCRIPT"
